/* eslint-disable react/prop-types */
import StoreProvider from "@/store/StoreProvider";
import "./globals.css";
import HeaderMain from "@/components/header/Header-main";
import Footer from "@/components/footer/Footer";


export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <StoreProvider>
          <HeaderMain/>
          {children}
          <Footer/>
        </StoreProvider>
      </body>
    </html>
  );
}
