/* eslint-disable react/prop-types */
import StoreProvider from "@/store/StoreProvider";
import "./globals.css";
import HeaderMain from "@/components/header/Header-main";
import Footer from "@/components/footer/Footer";
import TokenValidityChecker from "@/components/TokenValidityChecker";

export const metadata = {
  title: "Donuteria",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <StoreProvider>
          <TokenValidityChecker />
          <HeaderMain />
          <div id="modal"></div>
          {children}
          <Footer />
        </StoreProvider>
      </body>
    </html>
  );
}
