import StoreProvider from "@/store/StoreProvider";
import "./globals.css";
import HeaderMain from "@/components/header/header-main";


export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <StoreProvider>
          <HeaderMain/>
          {children}
        </StoreProvider>
      </body>
    </html>
  );
}
